*************************************************************************
*FUNCTION GRABAR_ITEM() && GRABAR ITEM FACTURAS/PEDIDOS/COTIZACION/NOTAS
*************************************************************************
*************************
**//GRABAR ITEM AL PEDIDO
*************************
SELECT 10 &&TEMPORAL REGISTROS 
SET ORDER TO 1 
FLOCK()
APPEND BLANK 
**//GRID1 /REGISTROS
	REPLACE CODIGO		WITH WCODIGO
	REPLACE DESCRIP		WITH WDESCRIP
	REPLACE DESCRIP2	WITH WDESCRIP2
	*REPLACE REFERENCIA	WITH WREFERENCIA
	*REPLACE MARCA		WITH WMARCA
	REPLACE CANT_PZA	WITH WCANT_PZA
	REPLACE CANTIDAD	WITH WCANTIDAD 
	REPLACE PRECIO		WITH WPRECIO   
	REPLACE DSCTO		WITH WDSCTO    
	REPLACE UNIDAD		WITH WUNIDAD   
	*REPLACE GARANTIA	WITH UPPER(WGARANTIA)
	REPLACE ALICUOTA	WITH WALICUOTA
	*REPLACE COSTO		WITH WCOSTO
	*REPLACE COSTO_PRO	WITH WCOSTO_PRO
	*REPLACE COSTO_US	WITH WCOSTO_US
	REPLACE DEPOSITO	WITH WDEPOSITO
	REPLACE TPRECIO		WITH WTPRECIO
	*REPLACE VALMONEDA	WITH WMONEDA_EX
	*REPLACE SERIAL		WITH UPPER(THISFORM.cSeriales.Value)
		
UNLOCK

RETURN


