****************************************************************
FUNCTION INDI(cARCHI,cINDEX)   && FUNCION DE TERMOMETRO INTERNO
****************************************************************
LOCAL cPORC:=LTRIM(STR((RECNO()/LASTREC()) * 100 ))
*PRIMERA=.F.
IF !lPRIMERA
   TITULO='Archivo =>'+ALLTRIM(cARCHI)+'.DBF'+'  Indice =>'+ALLTRIM(cINDEX)+'.NTX'
   PANTA(19,13,22,67,1)
   FOR I=20 TO 21
   @ I,14 SAY REPLICATE('±',53)
   NEXT I
   *PRIMERA=.T.
   lPRIMERA=.F.
ENDIF
IF cINDEX # cCOMP
   SET COLOR TO &CEL_SET
   @ 19,40 SAY 'Indice =>'+ALLTRIM(cINDEX)+'.NTX'
   cCOMP:=cINDEX
   nL:=14
   @ 19,14 SAY REPLICATE(" ",53)
   nTERDBF ++  
   nTERHOR:=RECNO()
ENDIF
SET COLOR TO &CEL_SET

// PORCENTAJE EJECUTADO POR ARCHIVO INDICE
nTERVER:=(VAL(cPORC)) / 2
IF nTERVER < 100  
SET COLOR TO &CEL_SET
@ 20,nL+nTERVER SAY (VAL(cPORC)+3) PICT "99%"
HELICE(val(cPORC),19,15)
ENDIF
@ 20,14 SAY REPLICATE(CHR(219),nTERVER) 
nDBF:=(nTERVER / nNTX) + nDBF1 
IF RECNO() == nTERHOR 
    IF !lPRIMERA
nDBF1 :=nTERHOR1
    ELSE
       lPRIMERA:=.F.
    ENDIF
ENDIF   
nTERHOR1:=nDBF
IF nDBF < 100 .AND. nDBF >= nCONTROLT
SET COLOR TO &CEL_SET
@ 21,14+nDBF SAY (nDBF * 2) PICT "99%"
nCONTROLT:=(nTERHOR1 - 10)
ENDIF
SET COLOR TO &CEL_SET
IF nDBF < 100
   @ 21,14 SAY REPLICATE(CHR(219),nDBF)
ENDIF
SET COLOR TO &CLR_SET
RETURN .T.
