CLEAR
SET SYSMENU SAVE   
SET SYSMENU TO     
DEFINE PAD padSys OF _MSYSMENU PROMPT '\<Ventas' COLOR SCHEME 3 ;
   KEY ALT+S, '' 
DEFINE PAD padEdit OF _MSYSMENU PROMPT '\<Inventario' COLOR SCHEME 3 ;
   KEY ALT+E, '' 
DEFINE PAD padRecord OF _MSYSMENU PROMPT '\<Compras' COLOR SCHEME 3 ;
   KEY ALT+R, '' 
DEFINE PAD padWindow OF _MSYSMENU PROMPT '\<Caja' COLOR SCHEME 3 ;
   KEY ALT+W, '' 
DEFINE PAD padReport OF _MSYSMENU PROMPT 'Re\<portes' COLOR SCHEME 3 KEY ALT+P, '' 
DEFINE PAD padExit OF _MSYSMENU PROMPT 'E\<xit' COLOR SCHEME 3 ;
   KEY ALT+X, ''
ON SELECTION MENU _MSYSMENU ;
   DO choice IN cliente WITH PAD(), MENU()
PROCEDURE choice
PARAMETER gcPad, gcMenu
WAIT WINDOW 'You chose ' + gcPad + ;
   ' from menu ' + gcMenu NOWAIT
IF gcPad = 'PADEXIT'
   SET SYSMENU TO DEFAULT
ENDIF